;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("-*- waybar -*-"
 (filename . "/home/geir/.config/waybar/config")
 (front-context-string . "// -*- mode: js ")
 (rear-context-string)
 (position . 1)
 (last-modified 26087 40563 475908 670000))
("-*- qutebrowser -*-"
 (filename . "~/.config/qutebrowser/config.py")
 (front-context-string . "# Autogenerated ")
 (rear-context-string)
 (position . 1)
 (last-modified 26065 58985 879991 238000))
("coo"
 (filename . "~/.config/doom/config.el")
 (front-context-string . "\n(global-set-key")
 (rear-context-string . "exp\n       )\n )\n")
 (position . 18285)
 (last-modified 26065 55817 856877 420000))
("-*- yasnippets -*-"
 (filename . "/home/geir/.config/doom/snippets/fundamental-mode/")
 (front-context-string . "  /home/geir/.co")
 (rear-context-string)
 (position . 1)
 (last-modified 26064 44763 662109 834000))
("-*- ~/.config/ -*-"
 (filename . "/home/geir/.config/")
 (front-context-string . "  /home/geir/.co")
 (rear-context-string)
 (position . 1)
 (last-modified 26064 42203 763043 934000))
("-*- comma/c/, -*-"
 (filename . "/home/geir/bin/c")
 (front-context-string . "#!/bin/python\n# ")
 (rear-context-string)
 (position . 1)
 (last-modified 26064 35104 19976 536000))
("-*- tmux -*-"
 (filename . "/home/geir/.config/tmux/tmux.conf")
 (front-context-string . "\"tmux capture-pi")
 (rear-context-string . "n C-t     popup ")
 (position . 2142)
 (last-modified 26056 61391 515511 133000))
("-*- zshrc | plugin development -*-"
 (filename . "/home/geir/.oh-my-zsh/custom/plugins/testing/testing.plugin.zsh")
 (front-context-string)
 (rear-context-string . "ting.plugin.zsh\n")
 (position . 58)
 (last-modified 26056 45366 725174 32000))
("org-capture-last-stored"
 (filename . "/home/geir/org/roam/20240305205428-syncthing.org")
 (front-context-string)
 (rear-context-string . "itle: Syncthing\n")
 (position . 87)
 (last-modified 26087 30836 824829 951000))
("-*- emacs | conf.d -*-"
 (filename . "~/.config/doom/conf.d/")
 (front-context-string . "_00-line-numbers")
 (rear-context-string . "61 Feb  9 22:48 ")
 (position . 80)
 (last-modified 26055 24736 467414 234000))
("-*- zshrc -*-"
 (filename . "~/.zshrc")
 (front-context-string . ")\n\nsource ${ZSH:")
 (rear-context-string . "ns+=(example foo")
 (position . 196)
 (last-modified 26055 24694 982779 597000))
("-*- sway config -*-"
 (filename . "~/.sway/config")
 (front-context-string . "\n# drag and drop")
 (rear-context-string . "_wrapping force\n")
 (position . 421)
 (last-modified 26055 16445 309027 744000))
)
