#!/usr/bin/env -S ansible-playbook -ilocalhost,
---
- hosts: localhost
  connection: local
  gather_facts: 0
  tasks:
  - raw: ansible-galaxy install -r ansible-galaxy-requirements.yml
    ignore_errors: 1

- hosts: localhost
  connection: local
  gather_facts: 1

  environment:
    SUDO_AKSPASS: >-
      {{ ansible_env.HOME }}

  vars:
    ansible_become_password: >-
      {{ lookup('community.general.passwordstore', 'local') }}

  environment:

  vars:
    pkg:
    - '@sway'
    - '@Development Tools'
    - cargo
    - figlet
    - firefox
    - fzf
    - gh
    - git
    - golang
    - pass
    - pre-commit
    - qutebrowser
    - rustc
    - tmux

  module_defaults:
    git:
      clone: 1
      depth: 1
      dest: ~/.local/src/

  post_tasks:
  # TODO banner with figlet command
  - include_tasks: tasks/_comment.yml
    vars:
      msg: DONE

  pre_tasks:
  - file: dest=~/.local/src state=directory

  - ansible.builtin.file:
      src: ~/.local/src/
      dest: ~/Sourcecode
      state: link

  handlers:
  - name: pip
    dnf: name=python-pip state=installed
    become: 1

  - name: mpm
    pip: name=meta-package-manager state=present

  - name: pkg
    dnf: name="{{ pkg }}" state=present
    become: 1

  - name: cron.allow
    dnf: name="{{ pkg }}" state=present
    become: 1

  tasks:

  - raw: "command -v {{ item }}"
    args:
      executable: /bin/bash
    register: res
    changed_when: res.rc != 0
    notify: "{{ item }}"
    with_items:
    - mpm

  - git: repo="{{ item }}" dest="{{ dest }}"
    with_items: "{{ git_repos[:limit] }}"
    ignore_errors: 1
    vars:
      limit: 4
      dest: >-
        ~/.local/src/{{ item.split('/')[-3:] | join('/') | replace('.git', '') | replace('github.com', 'github')}}
