#!/usr/bin/env -S ansible-playbook -ilocalhost,
---
- hosts: localhost
  connection: local
  gather_facts: 0
  tasks:

  - raw: ansible-galaxy install -r ansible-galaxy-requirements.yml
    ignore_errors: 0

- hosts: localhost
  connection: local
  gather_facts: 1

  environment:
    SUDO_AKSPASS: >-
      {{ ansible_env.HOME }}

  vars:
    ansible_become_password: >-
      {{ lookup('community.general.passwordstore', 'local') }}

  vars:
    go:
    - pup
    pip:
    - 'ansible-navigator[ansible-core]'
    yum:
    - '@Sway Desktop'
    - '@Development Tools'
    - firefox
    - qutebrowser
    - cargo
    - figlet
    - fzf
    - gh
    - git
    - golang
    - pass
    - pre-commit
    - rustc
    - tmux
    - waybar
    - realmd
    - sssd
    - krb5-workstation
    - krb5-libs
    - oddjob
    - oddjob-mkhomedir
    - samba-common-tools
    - python3-devel
    - libguestfs-devel
    - podman
    - podman-compose
    - gitui
    - tlp

  module_defaults:
    git:
      clone: 1
      depth: 1
      dest: ~/.local/src/
    dnf:
      state: present
    pip:
      state: present

  tasks:

  - ansible.builtin.shell:
      cmd: echo
    changed_when: 1
    notify:

  pre_tasks:
  - file: dest=~/.local/src state=directory

  - ansible.builtin.file:
      src: ~/.local/src/
      dest: ~/Sourcecode
      state: link

  handlers:
  - name: pip
    dnf: name=python-pip state=installed

  - name: mpm
    pip: name=meta-package-manager state=present

  - name: pkg
    dnf: name="{{ pkg }}" state=present

