#!/bin/bash
set -o errexit
set -o nounset

dir="$(dirname "$0")"
. /etc/os-release
distro=ID
release=VERSION_ID
pushd "$dir" || exit 1



if [[ ${SUDO_USER:-$'\0'} ]]; then
    # . "$dir"/bootstrap.d/${!distro}/${!release}
    if [ -s /etc/redhat-release ]
    then command dnf install --assumeyes make python-virtualenv python-pip gcc-go golang-bin cargo readline-devel
    fi
    exit 0
else

    command env SUDO_ASKPASS=~/bin/askpass sudo "$(realpath $0)"
fi

ln -sfrv ~/bin/{',',askpass}
command make -C "$dir"/src/pyenv/

. <("$HOME"/.pyenv/bin/pyenv init -)

pyenv global 3.12.0

# exit
# yadm config --get-regex python.env
# ./helpers/parse-gitconfig

for VENV in "$HOME"/.local/share/pyvenv/default; do
    [[ -d $VENV ]] && continue
    command python -mvenv "$VENV"
    "$VENV"/bin/pip install --upgrade pip
    "$VENV"/bin/pip install -r "$dir"/requirements.txt
done

crontab - <<CRONTAB
START_HOURS_RANGE=0-23
PATH=${PATH}
RANDOM_DELAY=2

*/10 * * * * yadm push
*/10 * * * * pass git push
CRONTAB

exit

for pip in "${HOME:-~}"/.pyvenv/bin/pip; do
    if [[ -f $pip ]]
    then
        "$pip" install --upgrade pip
        "$pip" install -r "$dir"/requirements.txt
        break
    fi
done

trap '${TMPDIR:+rm -rf${DEBUG:+v} $TMPDIR}' EXIT
PREFIX=${HOME:-~}
TMPDIR="$(mktemp -d /run/user/$(id -u)/XXXXX.tmp)"
mkdir --parents ${PREFIX:-/tmp}/.config/waybar/
pushd $TMPDIR  || exit 1
git clone --depth 1 https://github.com/catppuccin/waybar
pushd waybar
cp --recursive themes/ assets/ ${PREFIX:-/tmp}/.config/waybar/
ls "$TMPDIR"
