---
- git: repo=https://github.com/catppuccin/waybar dest=~/.local/share/src/waybar clone=1 depth=1

- file: path=~/.config/waybar/themes state=directory

- copy: remote_src=1 src="{{ item }}" dest="~/.config/waybar/themes/{{ item|basename }}"
  with_fileglob:
  - ~/.local/share/src/waybar/themes/*.css

- lineinfile:
    path: ~/.config/waybar/style.css
    regexp: >-
      ^@import .*
    line: >-
      @import "themes/macchiato.css"
