# -*- mode: yaml -*-
---
- hosts: localhost
  connection: local
  gather_facts: 0
  tasks:
  - include_tasks: "{{ item }}"
    with_items:
    - tasks/install/3rd_party.yml
    - tasks/install/fonts.yml
    - tasks/install/waybar_theme.yml

- hosts: localhost
  connection: local
  gather_facts: 1
  become: 1
  become_method: sudo
  no_log: 1

  vars:
    TRACK: stable
    OS: "{{ ansible_distribution }}"
    VERSION: "{{ ansible_distribution_version }}"
    UMASK: '077'

  module_defaults:
    ansible.builtin.yum_repository:
      file: third_party
    ansible.builtin.service:
      state: started
      enabled: true

  post_tasks:
  - raw: dnf makecache


  tasks:
  - name: Add DNF repositories
    include_tasks: "{{ item }}"
    with_fileglob:
    - "tasks/{{ ansible_pkg_mgr }}/*.yml"

  - user: name="{{ ansible_user_id }}" groups=systemd-journal,docker,input,audio,video
    when: ansible_user_id == 'root'

  - package: name=syncthing state=present

  - service: name="syncthing@{{ ansible_user_id }}.service"
    when: 0                     # TODO

  - service: name=osqueryd
    when: osquery_install is success

  - service: name=tailscaled
    when: tailscale_install is success
