---
- name: Tailscale repo
  ansible.builtin.yum_repository:
    name: "tailscale {{ TRACK }}"
    description: "Tailscale {{ TRACK }}"
    baseurl: >-
      https://pkgs.tailscale.com/{{ TRACK }}/{{ OS }}/{{ VERSION }}/$basearch
    gpgkey: >-
      https://pkgs.tailscale.com/{{ TRACK }}/{{ OS }}/{{ VERSION }}/repo.gpg
    repo_gpgcheck: 1
    gpgcheck: 0
  register: tailscale_repo
