#!/usr/bin/env python

"""
--------------------------------------------------------------------------------
NOTE sys.exceoption print zsh executable string; f.ex. python -mpip install --user MISSING_LIB
NOTE print org-agenda in zsh shells
NOTE fork this script to background so shell dont wait for io
NOTE print all TODO statements in git controlled dotfiles
--------------------------------------------------------------------------------
"""

from os import environ
from sys import import argv
from subprocess import run, Popen, PIPE, DEVNULL
from pathlib import Path
