#!/bin/bash

command yadm status --porcelain=v1 |
    while read -r line
    do read -r status file <<< "$line"
       [[ $line =~ ^[[:space:]]([[ADMT]]) ]]
       status=${BASH_REMATCH[1]}
       case $status in
           [AM]) yadm add "$file" ;;
           D)    yadm rm "$file"  ;;
           *)
       esac
    done

yadm status --porcelain=v1 | sed "s/^[[:space:]]/_/;/^A./s,,+,;/^D./s,-,,"

echo -n 'Commit?[y/N]'
read commit

echo -n 'Push?[y/N]'
read push

case $commit in
    [yY]) command yadm commit --message '.'
          ;;
    *)
esac

case $push in
    [yY]) command yadm push origin
          ;;
    *)
esac
