#!/bin/bash
command yadm status --porcelain=v1 |
    awk '/~$|\.elc$|\.pyc$/{system("yadm rm --cached -- "$NF)}
         /^ [AMT] /{system("yadm add "$NF)}
         /^ D /{system("yadm rm "$NF)}
         END{(system("yadm status"))}'

echo -n 'OK?[yN]'
read confirm
case $confirm in
    [yY])
        command yadm commit --message '.' && command yadm push origin
        ;;
    *)
esac
