#!/usr/bin/env bash

case $(readlink /proc/$PPID/exe) in
    *rofi*)
        selection="$*"
        if [ -n "$selection" ]; then
             :
        fi
        ;;
    *)  #
        command rofi -show pass -modi pass:"$HOME"/.local/script/___SOURCE__password-manager-passwords
esac
