#!/usr/bin/env python
from multiprocessing.dummy import Pool as ThreadPool
from multiprocessing import Pool as ProcessPool

from urllib.request import urlopen

def run_tasks(function, args, pool, chunk_size=None):
    results = pool.map(function, args, chunk_size)
    return results

def work(n):
    with urlopen("https://www.google.com/#{n}") as f:
        contents = f.read(32)
    return contents

if __name__ == '__main__':
    numbers = [x for x in range(1,100)]

    # Run the task using a thread pool

    t_p = ThreadPool()
    result = run_tasks(work, numbers, t_p)
    print (result)

    t_p.close()

    # Run the task using a process pool

    p_p = ProcessPool()
    result = run_tasks(work, numbers, p_p)
    print (result)

    p_p.close()
