#!/usr/bin/env bash

command stdbuf -oL env --chdir="${HOME}" --ignore-environment NO_COLOR=1 LC_ALL=C "$(which fd)" --one-file-system --ignore-file=$(___SOURCE__fd-ignore) --type=file --absolute-path --size=+1b `# --threads=8`
