#!/usr/bin/env zsh
if ! [[ $@ ]] ; then
    print '{'
    while IFS='=' read -r key value; do
        printf '"%s": "%s",' $key ${value}
    done | head -c -1
    print '}'
else
    for i; do
        case $i in
            --test)
                xargs -0n1 -a /proc/self/environ | $0 | command jq -cMs
            ;;
            --*)
                print "Usage: $0 [--test]"
            ;;
            *)
        esac
    done
fi

exit
